# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: CMPS Course Index
author: CMPS Department
logo: images/logo.png
copyright: ""
exclude_patterns: ["LICENSE.md", "README.md"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
#execute:
#  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex
html:
  navbar_number_sections : false
  home_page_in_navbar : true
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  google_analytics_id: UA-168693744-4
  baseurl : "https://courses.ok.ubc.ca/cmps/"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  use_issues_button: true
  use_repository_button: true
  comments:
    hypothesis: false
    utterances:
      repo: "ubco-cmps/course_index"
  extra_footer : |
      <div>
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>
          All content on this site (unless otherwise specified) is licensed under the <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0 license</a>
      </div>

# Information about where the book exists on the web
repository:
  url: https://github.com/ubco-cmps/course_index  # Online location of your book
  path_to_book: /  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

sphinx:
  config:
    html_show_copyright: false

parse:
  myst_extended_syntax: true